---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - env:
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:  #通过fieldRef引入到env中
                fieldPath: status.hostIP  #注入hostIP信息
        name: container-1
      - image: huangyaxuan/sentiment_test:latest
        name: test
        
